swagger: "2.0"
info:
  description: "This is the swagger file that goes with our server code"
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"  

basePath: "/api"

# Paths supported by the server application
paths:
  /categories:
    $ref: './swagger/categories.yml'
  /categories/{value}:
    $ref: './swagger/categories_ext.yml'
  /loot:
    $ref: './swagger/loot.yml'
  /tags:
    $ref: './swagger/tags.yml'
  /tags/{value}:
    $ref: './swagger/tags_ext.yml'
  /usages:
    $ref: './swagger/usages.yml'
  /usages/{value}:
    $ref: './swagger/usages_ext.yml'     
        
definitions:
  Loot:
    $ref: './swagger/loot_def.yml'